[2025-05-06T19:00:03.588+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-06T19:00:03.615+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_dag.run-dbt scheduled__2025-05-06T18:00:00+00:00 [queued]>
[2025-05-06T19:00:03.623+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_dag.run-dbt scheduled__2025-05-06T18:00:00+00:00 [queued]>
[2025-05-06T19:00:03.625+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-05-06T19:00:03.639+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run-dbt> on 2025-05-06 18:00:00+00:00
[2025-05-06T19:00:03.645+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3047) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-06T19:00:03.647+0000] {standard_task_runner.py:63} INFO - Started process 3054 to run task
[2025-05-06T19:00:03.646+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather_etl_dag', 'run-dbt', 'scheduled__2025-05-06T18:00:00+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/tmp/tmp_mzink41']
[2025-05-06T19:00:03.648+0000] {standard_task_runner.py:91} INFO - Job 88: Subtask run-dbt
[2025-05-06T19:00:03.663+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-06T19:00:03.697+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_etl_dag.run-dbt scheduled__2025-05-06T18:00:00+00:00 [running]> on host e97543d89996
[2025-05-06T19:00:03.781+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_etl_dag' AIRFLOW_CTX_TASK_ID='run-dbt' AIRFLOW_CTX_EXECUTION_DATE='2025-05-06T18:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-06T18:00:00+00:00'
[2025-05-06T19:00:03.783+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-06T19:00:06.237+0000] {logging_mixin.py:188} INFO - dbt run failed: Command '['dbt', 'run']' returned non-zero exit status 2.
[2025-05-06T19:00:06.238+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-05-06T19:00:06.238+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-06T19:00:06.249+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_etl_dag, task_id=run-dbt, run_id=scheduled__2025-05-06T18:00:00+00:00, execution_date=20250506T180000, start_date=20250506T190003, end_date=20250506T190006
[2025-05-06T19:00:06.273+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-05-06T19:00:06.290+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-06T19:00:06.292+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
